---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: opensuse-leap-42
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: distro_packages
    run_list:
      - recipe[test::distro_packages]
    excludes: # these lack distro packages
      - centos-6
      - centos-7
      - amazonlinux
      - amazonlinux-2
  - name: source
    run_list:
      - recipe[test::source]
  - name: epel
    run_list:
      - recipe[test::epel]
    includes:
      - centos-6
      - centos-7
      - freebsd-11
  - name: source
    run_list:
      - recipe[test::source]
  - name: upstream_repo
    run_list:
      - recipe[test::upstream_repo]
  - name: modules
    run_list:
      - recipe[test::modules]
    excludes:
      - centos-7-chef-13.3
      - ubuntu-16.04-chef-13.3
      - freebsd-11
  - name: passenger
    run_list:
      - recipe[test::passenger_packages]
    excludes:  # passenger distro install is not compatible with these
      - opensuse-leap-42
      - centos-6
      - centos-7
  - name: stream
    run_list:
      - recipe[test::stream]
